# Generated by Django 5.1.6 on 2025-03-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
